---
application:
  name: backoffice-demo
  port: 3000
  healthPath: /api/health

modules:
  config:
    - deploy/config.hcl

environments:
  demo:
    domain: backoffice-demo.sacha.house
    noIndex: true
    modules:
      group:
        - deploy/group-demo.hcl
      task:
        - deploy/task-demo.hcl

volume:
  mountPath: /var/lib/backoffice-demo

resources:
  cpu: 500
  memory: 1024
